### ISSUE TITLE
[layout] search field hides menu item

### ISSUE THREAD

**Issue by aneelia** [WebPurple/learn#29]
![image](https://user-images.githubusercontent.com/17769359/65081579-99d53580-d9ac-11e9-9b35-9b88fe3e77a0.png)

**Comment by ZeninZenin** [comment]
Ok. I know about this problem))
I suggest moving the “Search” to the right for higher resolutions. And for small resolutions make it fill the screen in width . 
How do you feel about it?

**Comment by aneelia** [comment]
Do you mean this? I think we can use it for all screens
![image](https://user-images.githubusercontent.com/17769359/65133785-ea2fb000-da0b-11e9-856d-793485b98d23.png)

**Comment by ZeninZenin** [comment]
Yes it`s suitable.
I thought about mobile phones too
![image](https://user-images.githubusercontent.com/37668430/65135996-88714500-da0f-11e9-82b2-19cd394e5251.png)

**Comment by aneelia** [comment]
It's not ok if user don't see menu
Do you have any similar ideas?
Maybe it'll be usability to show search field between header and central logo

**Comment by ZeninZenin** [comment]
It's about only `focused` state of `Search`.
![chrome-capture](https://user-images.githubusercontent.com/37668430/65145066-54068480-da21-11e9-9834-ac40ebbc6694.gif)
I can move it under the header.

**Comment by ZeninZenin** [comment]
for example
![chrome-capture (1)](https://user-images.githubusercontent.com/37668430/65145337-04748880-da22-11e9-8afc-a977da59421e.gif)

**Comment by aneelia** [comment]
Both of these variants are ..not good))
I mean we can make static search field for mobile phone
